//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int ClassId { get; set; }
        public string Phone { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string Hobbies { get; set; }
        public Nullable<bool> Football { get; set; }
        public Nullable<bool> Basketball { get; set; }
        public Nullable<bool> Cricket { get; set; }
        public Nullable<bool> Chess { get; set; }
        public Nullable<bool> Tennis { get; set; }
        public Nullable<bool> Drawing { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblDocument tblDocument { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual tblImage tblImage { get; set; }
    }
}
